### ISSUE TITLE
Front-end design 

### ISSUE THREAD

**Issue by lscott1967** [codeforkansascity/reusefull#2]
See reusefull.org for current site. Basic navigation and pages are defined. File containing content will be added soon, including blog posts. Priorities are Home, Get Stuff, including org profile form, and Give Stuff pages.

**Comment by lurejohn** [comment]
[Reusefull Sitemap.pdf](https://github.com/codeforkansascity/reusefull/files/3390457/Reusefull.Sitemap.pdf)
![reuseful-desktop-wireframes](https://user-images.githubusercontent.com/43890738/61189742-47e3fc80-a657-11e9-8a99-508bedf66a9d.jpg)
I'm attaching my sitemap and wireframe for the ReUseFull home page. Will you be at CodeKC tomorrow, or should we discuss at a later date? @lscott1967
