### ISSUE TITLE
Add textbox with guidance on giving 

### ISSUE THREAD

**Issue by lscott1967** [codeforkansascity/reusefull#24]
On the "Give Stuff" page, add a textbox with the following content: 

If you have torn or worn out clothing, never fear! Find a place for it here.

(Separate issue will be created for new page that lists orgs that accept torn and worn out clothing. We'll have to compile a list. Add link from "here.")

**Comment by lacrone** [comment]
Text box with link added. When we have orgs listed that accept unwearable clothing it will populate
