### ISSUE TITLE
Look into SSL cert for site

### ISSUE THREAD

**Issue by seanmk011289** [codeforkansascity/reusefull#40]
We can look into this with the hosting service.  And I'd be more than happy to take this on if I get login creds with whatever web host we are using.

**Comment by lacrone** [comment]
Hi Sean - we do have the SSL certificate in place with the hosting provider: https://reusefull.org/

**Comment by seanmk011289** [comment]
Sorry about that! It wasn't pulling up with the cert for me, but sounds good!
